// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_system_App.Entities;

[Table("Course")]
public partial class Course
{
    [Key]
    [Column("Crs_ID")]
    public int CrsId { get; set; }

    [Column("Crs_name")]
    [StringLength(50)]
    [Unicode(false)]
    public string CrsName { get; set; }

    [Column("Ins_ID")]
    public int? InsId { get; set; }

    [InverseProperty("Crs")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [ForeignKey("InsId")]
    [InverseProperty("Courses")]
    public virtual Instructor Ins { get; set; }

    [InverseProperty("Crs")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Crs")]
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    [InverseProperty("Crs")]
    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();
}