// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_system_App.Entities
{
    public partial class Department_SelectByNameResult
    {
        public int Dep_ID { get; set; }
        public string Dep_name { get; set; }
        public int? Manager_Id { get; set; }
    }
}
