// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_system_App.Entities;

[Table("Department")]
public partial class Department
{
    [Key]
    [Column("Dep_ID")]
    public int DepId { get; set; }

    [Column("Dep_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string DepName { get; set; }

    [Column("Manager_Id")]
    public int? ManagerId { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    [InverseProperty("Dept")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}