// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_system_App.Entities;

[Table("Exam")]
public partial class Exam
{
    [Key]
    [Column("Exam_ID")]
    public int ExamId { get; set; }

    public DateOnly? Date { get; set; }

    public int? Duration { get; set; }

    [Column("Crs_ID")]
    public int? CrsId { get; set; }

    [Column("Exam_Grade")]
    public int? ExamGrade { get; set; }

    [ForeignKey("CrsId")]
    [InverseProperty("Exams")]
    public virtual Course Crs { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<StudentExamQuestion> StudentExamQuestions { get; set; } = new List<StudentExamQuestion>();

    [ForeignKey("ExamId")]
    [InverseProperty("Exams")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}