// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_system_App.Entities
{
    public partial class Instructor_SelectResult
    {
        public int Ins_ID { get; set; }
        public string Ins_Name { get; set; }
        public int? Dept_Id { get; set; }
        public string ins_password { get; set; }
    }
}
