// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_system_App.Entities;

[Table("Question")]
public partial class Question
{
    [Key]
    [Column("Question_ID")]
    public int QuestionId { get; set; }

    [Required]
    [StringLength(20)]
    public string Type { get; set; }

    public int Grade { get; set; }

    [Required]
    [StringLength(255)]
    public string Body { get; set; }

    [Required]
    [Column("Model_Answer")]
    [StringLength(255)]
    public string ModelAnswer { get; set; }

    [Column("Crs_ID")]
    public int CrsId { get; set; }

    [ForeignKey("CrsId")]
    [InverseProperty("Questions")]
    public virtual Course Crs { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<StudentExamQuestion> StudentExamQuestions { get; set; } = new List<StudentExamQuestion>();

    [ForeignKey("QuestionId")]
    [InverseProperty("Questions")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}