// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_system_App.Entities
{
    public partial class Questions_SelectResult
    {
        public int Question_ID { get; set; }
        public string Type { get; set; }
        public int Grade { get; set; }
        public string Body { get; set; }
        public string Model_Answer { get; set; }
        public int Crs_ID { get; set; }
    }
}
