// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_system_App.Entities;

[PrimaryKey("QuestionId", "Choice")]
[Table("Question_Choices")]
public partial class QuestionChoice
{
    [Key]
    [Column("Question_ID")]
    public int QuestionId { get; set; }

    [Key]
    [StringLength(255)]
    public string Choice { get; set; }
}