// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_system_App.Entities
{
    public partial class Question_Student_Answer_ReportResult
    {
        public string Question { get; set; }
        public string Student_Answer { get; set; }
    }
}
