// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_system_App.Entities
{
    public partial class StudentExamQuestion_SelectResult
    {
        public int ST_ID { get; set; }
        public int Question_ID { get; set; }
        public int Exam_ID { get; set; }
        public string Student_Answer { get; set; }
    }
}
