// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_system_App.Entities
{
    public partial class StudentChooseCourseResult
    {
        public string Crs_name { get; set; }
        public int Crs_ID { get; set; }
    }
}
