// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exam_system_App.Entities
{
    public partial class studentLoginResult
    {
        public int St_ID { get; set; }
        public string ST_Fname { get; set; }
        public string ST_Lname { get; set; }
        public string ST_Email { get; set; }
        public string ST_Password { get; set; }
        public int Dept_Id { get; set; }
    }
}
